server:
  port: ${SERVER_PORT:8091}

spring:
  datasource:
    url: ${SPRING_DATASOURCE_URL_PROD}
    username: ${SPRING_DATASOURCE_USERNAME_PROD}
    password: ${SPRING_DATASOURCE_PASSWORD_PROD}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: validate
    open-in-view: false
    properties:
      hibernate:
        format_sql: true
        show_sql: false
  flyway:
    enabled: true
    locations: classpath:db/migration

app:
  nasa:
    apiKey: ${NASA_API_KEY}
    apodBaseUrl: ${APOD_BASE_URL:https://api.nasa.gov/planetary/apod}
    imagesBaseUrl: ${IMAGES_BASE_URL:https://images-api.nasa.gov}
  cloudflare:
    enabled: ${CF_AI_ENABLED:true}
    baseUrl: ${CF_AI_BASE_URL:https://api.cloudflare.com}
    accountId: ${CF_ACCOUNT_ID}
    cfAiProvider: ${CF_AI_PROVIDER:@cf}
    cfAiVendor: ${CF_AI_VENDOR:meta}
    cfAiModel: ${CF_AI_MODEL:llama-3-8b-instruct}
    cfTtsVendor: ${CF_TTS_VENDOR:deepgram}
    cfTtsModel: ${CF_TTS_MODEL:aura-2-en}
    apiToken: ${CF_API_TOKEN}
    maxVocabulary: ${CF_AI_MAX_VOCAB:3}
    temperature: ${CF_AI_TEMPERATURE:0.6}
    r2:
      account-id: ${R2_ACCOUNT_ID}
      access-key: ${R2_ACCESS_KEY}
      secret-key: ${R2_SECRET_KEY}
      bucket: ${R2_BUCKET}
      public-base-url: ${R2_PUBLIC_BASE_URL}

logging:
  level:
    root: INFO
    com.astrokiddo: INFO