server:
  port: ${SERVER_PORT}

spring:
  r2dbc:
    url: ${SPRING_R2DBC_URL_PROD}
    username: ${SPRING_R2DBC_USERNAME_PROD}
    password: ${SPRING_R2DBC_PASSWORD_PROD}
  flyway:
    enabled: true
    locations: classpath:db/migration
    url: ${SPRING_R2DBC_FLYWAY_URL_PROD}
    user: ${SPRING_R2DBC_USERNAME_PROD}
    password: ${SPRING_R2DBC_PASSWORD_PROD}

app:
  time-zone: ${APP_TIME_ZONE}
  nasa:
    apiKey: ${NASA_API_KEY}
    apodBaseUrl: ${APOD_BASE_URL}
    imagesBaseUrl: ${IMAGES_BASE_URL}
  cloudflare:
    enabled: ${CF_AI_ENABLED}
    baseUrl: ${CF_AI_BASE_URL}
    accountId: ${CF_ACCOUNT_ID}
    cfAiProvider: ${CF_AI_PROVIDER}
    cfAiVendor: ${CF_AI_VENDOR}
    cfAiModel: ${CF_AI_MODEL}
    cfTtsVendor: ${CF_TTS_VENDOR}
    cfTtsModel: ${CF_TTS_MODEL}
    apiToken: ${CF_API_TOKEN}
    maxVocabulary: ${CF_AI_MAX_VOCAB}
    temperature: ${CF_AI_TEMPERATURE}
    r2:
      account-id: ${R2_ACCOUNT_ID}
      access-key: ${R2_ACCESS_KEY}
      secret-key: ${R2_SECRET_KEY}
      bucket: ${R2_BUCKET}
      public-base-url: ${R2_PUBLIC_BASE_URL}

logging:
  level:
    root: INFO
    com.astrokiddo: INFO